"""
Django settings for demo_project project.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE_DIR = os.path.join(BASE_DIR, "templates")
STATIC_DIR = os.path.join(BASE_DIR, "static")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*5f(@8l1d_da4&=pqdc0u0@klous*&d#omu(3gn($ewnk)asp_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'social_django',
    'library.apps.LibraryConfig',
    'demo_project',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'demo_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'demo_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    STATIC_DIR,
]

# Redirect to home URL after login (Default redirects to /accounts/profile/)
# LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/library/'
LOGOUT_REDIRECT_URL = '/library/'


EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# AUTHENTICATION_BACKENDS = (
#  'social_core.backends.open_id.OpenIdAuth',  # for Google authentication
#  'social_core.backends.google.GoogleOpenId', # for Google authentication
#  'social_core.backends.google.GoogleOAuth2',  # for Google authentication
#  'social_core.backends.google.GoogleOAuth',
#  'django.contrib.auth.backends.ModelBackend',
  
# )


# SOCIAL_AUTH_PIPELINE = [  # Note: Sequence of functions matters here.
#     'social.pipeline.social_auth.social_details',  # 0
#     'social.pipeline.social_auth.social_uid',  # 1
#     'social.pipeline.social_auth.auth_allowed',  # 2
#     'social.pipeline.social_auth.social_user',  # 3
#     'social.pipeline.user.get_username',  # 4
#     'social.pipeline.social_auth.associate_by_email',  # 5
#     'social.pipeline.social_auth.associate_user',  # 6
#     'social.pipeline.social_auth.load_extra_data',  # 7
#     'social.pipeline.user.user_details',  # 8
# ]


# SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = ' https://developers.google.com/identity/protocols/OAuth2WebServer'  #Paste Client ID
# SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'https://developers.google.com/identity/protocols/OAuth2WebServer' #Paste Client Secret


DEFAULT_AUTO_FIELD='django.db.models.AutoField'
